Repository th-koeln/open-product-evaluation-server, pull requests merged in 2018-10, with the labels that each got.

#145 Feature/test
  .eslintrc.json
  .travis.yml
  config.js
  package-lock.json
  package.json
  seeds/data/context/context.js
  seeds/data/survey/survey.js
  test/__snapshots__/context.test.js.snap
  test/__snapshots__/device.test.js.snap
  test/__snapshots__/question.test.js.snap
  test/__snapshots__/survey.test.js.snap
  test/__snapshots__/user.test.js.snap
  test/context.test.js
  test/device.test.js
  test/helpers.js
  test/question.test.js
  test/requesthelper.js
  test/setup.js
  test/survey.test.js
  test/user.test.js
Labels: testing

#151 users can see every device, but only edit their own
  src/entities/device/device.resolvers.js
Labels: graphql

#164 Fixes
  src/entities/question/question.graphql
  src/entities/question/question.model.js
  src/entities/user/user.graphql
Labels: bug, graphql, usability
