Repository th-koeln/open-product-evaluation-server, pull requests merged in 2018-09, with the labels that each got.

#103 Feature/new auth system
  src/entities/context/context.graphql
  src/entities/context/context.model.js
  src/entities/context/context.resolvers.js
  src/entities/context/context.schema.js
  src/entities/device/device.graphql
  src/entities/device/device.model.js
  src/entities/device/device.resolvers.js
  src/entities/device/device.schema.js
  src/entities/image/image.model.js
  src/entities/survey/survey.resolvers.js
  src/entities/survey/survey.schema.js
  src/entities/user/user.resolvers.js
  src/entities/vote/vote.resolvers.js
  src/entities/vote/vote.schema.js
  src/utils/permissionMiddleware.js
Labels: feedback

#104 Questions rework
  package-lock.json
  src/entities/context/context.model.js
  src/entities/image/image.graphql
  src/entities/image/image.model.js
  src/entities/image/image.resolvers.js
  src/entities/image/image.schema.js
  src/entities/question/question.graphql
  src/entities/question/question.model.js
  src/entities/question/question.resolvers.js
  src/entities/question/question.schema.js
  src/entities/survey/survey.model.js
  src/index.js
  src/utils/answerStore.js
  src/utils/dbLoader.js
  src/utils/idStore.js
  src/utils/imageStore.js
  src/utils/permissionMiddleware.js
Labels: graphql, mongodb

#106 Pubsub
  src/entities/context/context.graphql
  src/entities/context/context.model.js
  src/entities/context/context.resolvers.js
  src/entities/device/device.graphql
  src/entities/device/device.model.js
  src/entities/device/device.resolvers.js
  src/entities/image/image.model.js
  src/entities/question/question.model.js
  src/entities/survey/survey.model.js
  src/entities/user/user.graphql
  src/entities/user/user.model.js
  src/entities/user/user.resolvers.js
  src/entities/vote/vote.graphql
  src/entities/vote/vote.resolvers.js
  src/entities/vote/vote.schema.js
  src/index.js
  src/utils/answerStore.js
  src/utils/pubsubChannels.js
  src/utils/pubsubEmitter.js
  src/utils/subscriptionEvents.js
Labels: graphql, mongodb, sockets

#107 changed seeds to match new mongoose schemas
  seeds/data/image/image.js
  seeds/data/question/question.js
  seeds/data/survey/survey.js
  seeds/data/vote/vote.js
  src/entities/survey/survey.schema.js
Labels: mongodb

#109 Fixes
  src/entities/device/device.resolvers.js
  src/entities/image/image.resolvers.js
  src/entities/question/question.graphql
  src/entities/question/question.resolvers.js
  src/entities/survey/survey.resolvers.js
Labels: bug

#111 Fixes
  seeds/data/device/device.js
  seeds/data/question/question.js
  seeds/data/vote/vote.js
  seeds/voteGenerator.js
  src/entities/context/context.model.js
  src/entities/context/context.schema.js
  src/entities/device/device.schema.js
  src/entities/question/question.model.js
  src/entities/question/question.resolvers.js
  src/entities/survey/survey.resolvers.js
  src/entities/survey/survey.schema.js
  src/entities/vote/vote.model.js
  src/entities/vote/vote.schema.js
Labels: graphql, mongodb

#113 Fixes
  seeds/data/user/user.js
  seeds/data/vote/vote.js
  seeds/voteGenerator.js
  src/entities/question/question.graphql
  src/entities/question/question.resolvers.js
  src/entities/user/user.resolvers.js
  src/entities/user/user.schema.js
  src/entities/vote/vote.graphql
  src/entities/vote/vote.resolvers.js
  src/entities/vote/vote.schema.js
  src/utils/answerStore.js
  src/utils/passwordSaltHash.js
Labels: graphql, mongodb

#115 quick fixes
  src/utils/pubsubEmitter.js
Labels: graphql

#122 Even more Fixes
  src/entities/context/context.resolvers.js
  src/entities/image/image.graphql
  src/entities/image/image.resolvers.js
  src/utils/permissionMiddleware.js
Labels: graphql, mongodb

#127 added lazy cors settings
  src/index.js
Labels: graphql

#134 More and more Fixes
  src/entities/context/context.resolvers.js
  src/entities/image/image.resolvers.js
  src/entities/survey/survey.resolvers.js
  src/entities/user/user.graphql
  src/entities/user/user.model.js
  src/entities/user/user.resolvers.js
  src/entities/vote/vote.model.js
Labels: bug, graphql, mongodb

#142 Schneller bugfix
  seeds/voteGenerator.js
  src/entities/context/context.resolvers.js
Labels: bug
