Repository th-koeln/open-product-evaluation-server, pull requests merged in 2019-02, with the labels that each got.

#191 Fix/commands
  .gitignore
  config.js
  package.json
  src/index.js
Labels: graphql

#192 Fix/mongo connection
  package-lock.json
  package.json
  src/utils/dbLoader.js
Labels: graphql, mongodb

#203 SCSS
  admin/src/components/AppEditor.vue
  admin/src/components/AppNavigation.vue
  admin/src/components/AppWrapper.vue
  admin/src/components/account/LoginForm.vue
  admin/src/components/client/ClientList.vue
  admin/src/components/domain/Domain.vue
  admin/src/components/domain/DomainEdit.vue
  admin/src/components/domain/DomainList.vue
  admin/src/components/misc/ImageContainer.vue
  admin/src/components/misc/OpenSourceNote.vue
  admin/src/components/misc/SearchInput.vue
  admin/src/components/question/ChoiceOptions.vue
  admin/src/components/question/FavoriteOptions.vue
  admin/src/components/question/Items.vue
  admin/src/components/question/LikeDislikeOptions.vue
  admin/src/components/question/LikeOptions.vue
  admin/src/components/question/QuestionItem.vue
  admin/src/components/question/RegulatorOptions.vue
  admin/src/components/survey/Survey.vue
  admin/src/components/survey/SurveyFormEdit.vue
  admin/src/components/survey/SurveyList.vue
  admin/src/components/votes/Votes.vue
  admin/src/main.js
  admin/src/scss/autocomplete.scss
  admin/src/scss/base.scss
  admin/src/scss/bootstrap.scss
  admin/src/scss/elements.scss
  admin/src/scss/global.scss
  admin/src/scss/index.scss
  admin/src/scss/tags.scss
  admin/src/scss/variables.scss
  admin/src/scss/visualisation.scss
Labels: frontend

#202 Form submission
  admin/src/App.vue
  admin/src/components/account/ProfileForm.vue
  admin/src/components/client/ClientEdit.vue
  admin/src/components/client/ClientList.vue
  admin/src/components/domain/DomainList.vue
  admin/src/components/misc/ErrorAlert.vue
  admin/src/components/misc/SuccessAlert.vue
  admin/src/components/user/UserEdit.vue
  admin/src/components/user/UserList.vue
  admin/src/store/modules/clients.js
  admin/src/store/modules/domain.js
  admin/src/store/modules/form.js
  admin/src/store/modules/user.js
  admin/src/store/store.js
Labels: frontend

#215 Reorder items choices labels now available
  seeds/data/question/question.js
  seeds/data/survey/survey.js
  src/entities/question/question.graphql
  src/entities/question/question.model.js
  src/entities/question/question.resolvers.js
  src/entities/question/question.schema.js
  src/entities/survey/survey.graphql
  src/entities/survey/survey.model.js
  src/entities/survey/survey.resolvers.js
  src/entities/survey/survey.schema.js
Labels: graphql, mongodb

#214 SetItemImage response fixed
  src/entities/question/question.resolvers.js
Labels: graphql

#213 Amount queries
  src/entities/client/client.graphql
  src/entities/client/client.resolvers.js
  src/entities/domain/domain.graphql
  src/entities/domain/domain.resolvers.js
  src/entities/survey/survey.graphql
  src/entities/survey/survey.resolvers.js
  src/entities/user/user.graphql
  src/entities/user/user.resolvers.js
  src/entities/vote/vote.graphql
  src/entities/vote/vote.resolvers.js
  src/utils/permissionMiddleware.js
Labels: graphql

#212 Query filter
  package-lock.json
  package.json
  src/entities/client/client.graphql
  src/entities/client/client.resolvers.js
  src/entities/domain/domain.graphql
  src/entities/domain/domain.resolvers.js
  src/entities/misc/misc.graphql
  src/entities/misc/misc.resolvers.js
  src/entities/survey/survey.graphql
  src/entities/survey/survey.resolvers.js
  src/entities/user/user.graphql
  src/entities/user/user.resolvers.js
  src/entities/vote/vote.graphql
  src/entities/vote/vote.resolvers.js
  src/utils/dbQueryBuilder.js
Labels: graphql

#211 Fix/survey image
  config.js
  src/entities/image/image.graphql
  src/entities/image/image.resolvers.js
  src/entities/image/image.schema.js
  src/entities/survey/survey.graphql
  src/entities/survey/survey.resolvers.js
  src/utils/permissionMiddleware.js
  test/__snapshots__/survey.test.js.snap
Labels: graphql, mongodb

#210 Reset a questions default values on type change
  src/entities/question/question.resolvers.js
Labels: mongodb

#209 Add question at position
  src/entities/question/question.graphql
  src/entities/question/question.model.js
  src/entities/question/question.resolvers.js
  src/entities/survey/survey.model.js
Labels: graphql, mongodb

#206 Frontend
  admin/package-lock.json
  admin/src/api/domain.js
  admin/src/api/question.js
  admin/src/api/survey.js
  admin/src/components/AppNavigation.vue
  admin/src/components/AppWrapper.vue
  admin/src/components/account/ProfileForm.vue
  admin/src/components/account/RegisterForm.vue
  admin/src/components/client/ClientEdit.vue
  admin/src/components/client/ClientList.vue
  admin/src/components/domain/Domain.vue
  admin/src/components/domain/DomainEdit.vue
  admin/src/components/domain/DomainList.vue
  admin/src/components/domain/DomainNew.vue
  admin/src/components/misc/EmptyState.vue
  admin/src/components/misc/OpenSourceNote.vue
  admin/src/components/question/ChoiceOptions.vue
  admin/src/components/question/FavoriteOptions.vue
  admin/src/components/question/Items.vue
  admin/src/components/question/LikeDislikeOptions.vue
  admin/src/components/question/LikeOptions.vue
  admin/src/components/question/Question.vue
  admin/src/components/question/QuestionItem.vue
  admin/src/components/question/QuestionList.vue
  admin/src/components/question/RankingOptions.vue
  admin/src/components/question/RegulatorOptions.vue
  admin/src/components/question/elements/Choice.vue
  admin/src/components/question/elements/ContextMenu.vue
  admin/src/components/question/elements/Description.vue
  admin/src/components/question/elements/Items.vue
  admin/src/components/question/elements/Label.vue
  admin/src/components/question/types/ChoiceQuestion.vue
  admin/src/components/question/types/FavoriteQuestion.vue
  admin/src/components/question/types/LikeDislikeQuestion.vue
  admin/src/components/question/types/LikeQuestion.vue
  admin/src/components/question/types/RankingQuestion.vue
  admin/src/components/question/types/RegulatorQuestion.vue
  admin/src/components/survey/Survey.vue
  admin/src/components/survey/SurveyFormEdit.vue
  admin/src/components/survey/SurveyFormNew.vue
  admin/src/components/survey/SurveyList.vue
  admin/src/components/user/UserEdit.vue
  admin/src/components/user/UserList.vue
  admin/src/components/votes/Chart.vue
  admin/src/components/votes/Results.vue
  admin/src/components/votes/Visualisation.vue
  admin/src/components/votes/Votes.vue
  admin/src/main.js
  admin/src/router/index.js
  admin/src/scss/base.scss
  admin/src/store/modules/clients.js
  admin/src/store/modules/domain.js
  admin/src/store/modules/form.js
  admin/src/store/modules/questions.js
  admin/src/store/modules/survey.js
  static/images/default/eval1.jpeg
  static/images/default/eval2.jpeg
Labels: frontend

#218 Fix/hashID
  admin/src/api/clients.js
  admin/src/api/domain.js
  admin/src/api/question.js
  admin/src/api/survey.js
  admin/src/api/user.js
  src/entities/client/client.graphql
  src/entities/client/client.resolvers.js
  src/entities/domain/domain.graphql
  src/entities/domain/domain.resolvers.js
  src/entities/image/image.graphql
  src/entities/image/image.resolvers.js
  src/entities/question/question.graphql
  src/entities/question/question.resolvers.js
  src/entities/survey/survey.graphql
  src/entities/survey/survey.resolvers.js
  src/entities/user/user.graphql
  src/entities/user/user.resolvers.js
  src/entities/vote/vote.graphql
  src/entities/vote/vote.resolvers.js
  src/utils/answerStore.js
  src/utils/authUtils.js
Labels: graphql

#220 Https
  .gitignore
  config.js
  src/index.js
  src/views/utils/client.js
  vue.config.js
Labels: frontend, graphql

#221 Visualisation
  package-lock.json
  package.json
  src/views/components/AppNavigation.vue
  src/views/components/AppWrapper.vue
  src/views/components/client/ClientList.vue
  src/views/components/domain/DomainList.vue
  src/views/components/misc/OpenSourceNote.vue
  src/views/components/question/Question.vue
  src/views/components/question/QuestionList.vue
  src/views/components/question/elements/Choice.vue
  src/views/components/question/elements/ContextMenu.vue
  src/views/components/question/elements/Items.vue
  src/views/components/question/elements/Label.vue
  src/views/components/question/types/ChoiceQuestion.vue
  src/views/components/question/types/RegulatorQuestion.vue
  src/views/components/survey/Survey.vue
  src/views/components/survey/SurveyFormEdit.vue
  src/views/components/survey/SurveyList.vue
  src/views/components/user/UserList.vue
  src/views/components/votes/Chart.vue
  src/views/components/votes/Votes.vue
  src/views/scss/base.scss
  src/views/scss/variables.scss
Labels: frontend, graphql

#224 Setup
  .travis.yml
  README.md
  config.js
  install.js
  package-lock.json
  package.json
  seeds/seeder.js
  tests/api/__snapshots__/user.test.js.snap
  tests/api/client.test.js
  tests/api/domain.test.js
  tests/api/question.test.js
  tests/api/setup.js
  tests/api/survey.test.js
  tests/api/user.test.js
Labels: frontend, graphql, mongodb

#225 Lint
  .eslintrc.js
  package-lock.json
  package.json
Labels: testing

#226 Responsive images
  config.js
  package-lock.json
  package.json
  seeds/data/image/image.js
  seeds/data/question/question.js
  src/entities/image/image.resolvers.js
  src/entities/question/question.graphql
  src/entities/question/question.resolvers.js
  src/index.js
  src/store/image.store.js
  src/utils/database.js
  static/images/default/angry.png
  static/images/default/dislikeIcon.png
  static/images/default/eval1.jpeg
  static/images/default/eval2.jpeg
  static/images/default/happy.png
  static/images/default/likeIcon.png
Labels: graphql, mongodb

#223 Pagination
  package-lock.json
  package.json
  src/views/api/clients.js
  src/views/api/domain.js
  src/views/api/survey.js
  src/views/api/user.js
  src/views/components/client/ClientList.vue
  src/views/components/domain/DomainEdit.vue
  src/views/components/domain/DomainList.vue
  src/views/components/domain/DomainNew.vue
  src/views/components/survey/SurveyFormEdit.vue
  src/views/components/survey/SurveyList.vue
  src/views/components/user/UserList.vue
  src/views/main.js
  src/views/router/index.js
  src/views/scss/base.scss
  src/views/store/modules/clients.js
  src/views/store/modules/domain.js
  src/views/store/modules/survey.js
  src/views/store/modules/user.js
Labels: frontend

#227 better subscription implementation
  src/views/api/auth.js
  src/views/api/clients.js
  src/views/api/domain.js
  src/views/api/question.js
  src/views/api/survey.js
  src/views/api/user.js
  src/views/components/survey/Survey.vue
  src/views/components/votes/Results.vue
  src/views/store/modules/auth.js
  src/views/store/modules/domain.js
  src/views/store/modules/survey.js
  src/views/utils/client.js
Labels: frontend, graphql

#231 Frontend fixes
  src/views/api/domain.js
  src/views/api/question.js
  src/views/components/client/ClientList.vue
  src/views/components/domain/DomainEdit.vue
  src/views/components/misc/Grid.vue
  src/views/components/preview/FavoritePreview.vue
  src/views/components/preview/ItemPreview.vue
  src/views/components/preview/LikeDislikePreview.vue
  src/views/components/preview/LikePreview.vue
  src/views/components/preview/RankingPreview.vue
  src/views/components/preview/RegulatorPreview.vue
  src/views/components/user/UserList.vue
  src/views/store/modules/auth.js
  src/views/utils/client.js
Labels: frontend

#238 Csv Export
  config.js
  package-lock.json
  package.json
  seeds/voteGenerator.js
  src/controls/version.control.js
  src/entities/version/version.resolvers.js
  src/index.js
  src/routes/exports.js
  src/routes/images.js
  src/store/answer.store.js
  src/store/image.store.js
  src/subscriptions/emitter.js
  src/utils/sort.js
  src/visualization/csv.creator.js
Labels: graphql, mongodb

#240 Fix/answer update
  src/entities/vote/vote.graphql
  src/entities/vote/vote.resolvers.js
Labels: graphql

#245 Csv export
  src/routes/exports.js
  src/visualization/csv.creator.js
Labels: graphql

#246 Frontend
  src/views/api/survey.js
  src/views/components/account/ProfileForm.vue
  src/views/components/client/ClientEdit.vue
  src/views/components/domain/DomainEdit.vue
  src/views/components/domain/DomainNew.vue
  src/views/components/survey/Survey.vue
  src/views/components/survey/SurveyFormEdit.vue
  src/views/components/survey/SurveyFormNew.vue
  src/views/components/user/UserEdit.vue
  src/views/components/user/UserList.vue
  src/views/components/votes/Chart.vue
  src/views/components/votes/Results.vue
  src/views/components/votes/Visualisation.vue
  src/views/components/votes/Votes.vue
  src/views/store/modules/results.js
  src/views/store/modules/survey.js
Labels: frontend

#244 Rework/filter
  src/entities/client/client.graphql
  src/entities/client/client.resolvers.js
  src/entities/domain/domain.graphql
  src/entities/domain/domain.resolvers.js
  src/entities/misc/misc.graphql
  src/entities/misc/misc.resolvers.js
  src/entities/survey/survey.graphql
  src/entities/survey/survey.resolvers.js
  src/entities/user/user.graphql
  src/entities/user/user.resolvers.js
  src/entities/vote/vote.graphql
  src/entities/vote/vote.resolvers.js
  src/utils/filter.js
Labels: graphql
