Repository th-koeln/open-product-evaluation-server, pull requests merged in 2019-03, with the labels that each got.

#248 Frontend
  src/views/api/clients.js
  src/views/api/domain.js
  src/views/components/client/ClientEdit.vue
  src/views/components/domain/DomainEdit.vue
  src/views/components/misc/SearchInput.vue
  src/views/store/modules/clients.js
  src/views/store/modules/domain.js
Labels: frontend

#249 changed label of FAVORITE / RANKING questions evaluation data
  src/visualization/evaluation.creator.js
Labels: graphql

#250 Rework/client registration
  seeds/data/client/client.js
  src/entities/client/client.graphql
  src/entities/client/client.model.js
  src/entities/client/client.resolvers.js
  src/entities/client/client.schema.js
  src/entities/domain/domain.resolvers.js
  src/entities/question/question.resolvers.js
  src/entities/results/csv.creator.js
  src/entities/results/evaluation.creator.js
  src/entities/results/summary.creator.js
  src/entities/survey/survey.resolvers.js
  src/entities/user/user.resolvers.js
  src/entities/version/version.control.js
  src/entities/version/version.resolvers.js
  src/entities/vote/vote.resolvers.js
  src/middleware/permission.middelware.js
  src/routes/exports.js
  src/store/answer.store.js
  src/subscriptions/emitter.js
  src/utils/auth.js
  src/utils/checks.js
  src/utils/lifetime.js
Labels: graphql, mongodb

#254 Frontend bug fixes
  package-lock.json
  package.json
  src/views/api/clients.js
  src/views/api/user.js
  src/views/components/AppNavigation.vue
  src/views/components/account/LoginForm.vue
  src/views/components/account/ProfileForm.vue
  src/views/components/account/RegisterForm.vue
  src/views/components/client/ClientEdit.vue
  src/views/components/client/ClientList.vue
  src/views/components/domain/DomainEdit.vue
  src/views/components/domain/DomainList.vue
  src/views/components/domain/DomainNew.vue
  src/views/components/misc/ImageContainer.vue
  src/views/components/misc/SearchInput.vue
  src/views/components/preview/ChoicePreview.vue
  src/views/components/preview/FavoritePreview.vue
  src/views/components/preview/ItemPreview.vue
  src/views/components/preview/LikeDislikePreview.vue
  src/views/components/preview/LikePreview.vue
  src/views/components/preview/Preview.vue
  src/views/components/preview/QuestionPreview.vue
  src/views/components/preview/RankingPreview.vue
  src/views/components/preview/RegulatorPreview.vue
  src/views/components/question/Question.vue
  src/views/components/question/QuestionList.vue
  src/views/components/question/elements/Choice.vue
  src/views/components/question/elements/ContextMenu.vue
  src/views/components/question/elements/Items.vue
  src/views/components/question/elements/Label.vue
  src/views/components/question/types/ChoiceQuestion.vue
  src/views/components/question/types/LikeDislikeQuestion.vue
  src/views/components/question/types/LikeQuestion.vue
  src/views/components/question/types/RegulatorQuestion.vue
  src/views/components/survey/Survey.vue
  src/views/components/survey/SurveyFormEdit.vue
  src/views/components/survey/SurveyList.vue
  src/views/components/user/UserEdit.vue
  src/views/components/user/UserList.vue
  src/views/components/votes/Chart.vue
  src/views/components/votes/Results.vue
  src/views/components/votes/Votes.vue
  src/views/main.js
  src/views/router/index.js
  src/views/scss/base.scss
  src/views/store/modules/clients.js
  src/views/store/modules/user.js
Labels: frontend

#251 Documentation
  .gitignore
  .travis.yml
  README.md
  src/entities/client/client.graphql
  src/entities/client/client.model.js
  src/entities/client/client.resolvers.js
  src/entities/domain/domain.graphql
  src/entities/domain/domain.model.js
  src/entities/image/image.graphql
  src/entities/misc/misc.graphql
  src/entities/question/question.graphql
  src/entities/survey/survey.graphql
  src/entities/user/user.graphql
  src/entities/version/version.graphql
  src/entities/vote/vote.graphql
  src/middleware/permission.middelware.js
  src/store/image.store.js
Labels: graphql

#258 Regulator questions
  package-lock.json
  src/entities/client/client.resolvers.js
  src/entities/question/question.graphql
  src/entities/question/question.resolvers.js
  src/entities/vote/vote.graphql
  src/store/answer.store.js
Labels: graphql, mongodb

#260 removed minor bugs
  src/entities/question/question.resolvers.js
Labels: graphql

#259 Added functional tests
  src/views/components/client/ClientEdit.vue
  src/views/components/client/ClientList.vue
  src/views/components/domain/DomainEdit.vue
  src/views/components/domain/DomainList.vue
  src/views/components/question/Question.vue
  src/views/components/question/elements/ContextMenu.vue
  src/views/components/question/elements/Items.vue
  src/views/components/survey/SurveyList.vue
  src/views/components/user/UserEdit.vue
  src/views/components/user/UserList.vue
  src/views/components/votes/Votes.vue
  tests/e2e/fixtures/clients.json
  tests/e2e/fixtures/domain.json
  tests/e2e/fixtures/surveys/existing.json
  tests/e2e/fixtures/surveys/new.json
  tests/e2e/fixtures/users/user.json
  tests/e2e/specs/account/login.js
  tests/e2e/specs/account/profile.js
  tests/e2e/specs/account/register.js
  tests/e2e/specs/client/client.js
  tests/e2e/specs/domain/domain.js
  tests/e2e/specs/survey/choice.js
  tests/e2e/specs/survey/favorite.js
  tests/e2e/specs/survey/like.js
  tests/e2e/specs/survey/likedislike.js
  tests/e2e/specs/survey/questions.js
  tests/e2e/specs/survey/ranking.js
  tests/e2e/specs/survey/regulator.js
  tests/e2e/specs/survey/survey.js
  tests/e2e/specs/user/edit.js
  tests/e2e/specs/user/user.js
  tests/e2e/support/commands.js
Labels: testing

#261 Client code
  src/entities/client/client.graphql
  src/entities/client/client.resolvers.js
Labels: graphql

#262 Frontend
  src/views/api/clients.js
  src/views/api/question.js
  src/views/components/client/ClientEdit.vue
  src/views/components/question/types/RegulatorQuestion.vue
  src/views/components/votes/Results.vue
  src/views/components/votes/Votes.vue
  src/views/store/modules/questions.js
Labels: frontend

#268 Integration tests
  src/entities/domain/domain.resolvers.js
Labels: graphql
